import { Link } from '@tanstack/react-router'; import { useEffect,useRef,useState } from 'react'; import { ArrowRight,CalendarDays,MapPin } from 'lucide-react'; import type { Program } from '@/data/programs'; import type { EventItem } from '@/data/events'; import type { Post } from '@/data/posts'; import type { Person } from '@/data/team'; import mountain from '@/assets/himalayan-community.jpg';
export function SectionHeading({eyebrow,title,copy,center=false}:{eyebrow:string;title:string;copy?:string;center?:boolean}){return <header className={`mb-12 max-w-2xl ${center?'mx-auto text-center':''}`}><p className="mb-3 text-sm font-semibold uppercase tracking-[.18em] text-accent">{eyebrow}</p><h2 className="text-primary">{title}</h2><div className={`mt-4 h-0.5 w-16 bg-brass ${center?'mx-auto':''}`}/>{copy&&<p className="mt-5 text-muted-foreground">{copy}</p>}</header>}
export function StatCounter({value,label}:{value:number;label:string}){const ref=useRef<HTMLDivElement>(null);const [n,setN]=useState(0);useEffect(()=>{const el=ref.current;if(!el)return;const obs=new IntersectionObserver(([e])=>{if(!e.isIntersecting)return;let s=0;const t=setInterval(()=>{s+=Math.max(1,Math.ceil(value/40));setN(Math.min(s,value));if(s>=value)clearInterval(t)},25);obs.disconnect()});obs.observe(el);return()=>obs.disconnect()},[value]);return <div ref={ref} className="text-center"><strong className="font-display text-4xl text-primary">{n.toLocaleString()}{value>=1000?'k+':'+'}</strong><p className="mt-1 text-sm font-medium text-muted-foreground">{label}</p></div>}
export function ProgramCard({item}:{item:Program}){return <article className="card-lift flex h-full flex-col rounded-2xl border bg-card p-7"><p className="text-xs font-semibold uppercase tracking-[.16em] text-accent">{item.eyebrow}</p><h3 className="mt-3 text-2xl text-primary">{item.title}</h3><p className="mt-3 flex-1 text-muted-foreground">{item.description}</p><Link to="/programs/$slug" params={{slug:item.slug}} className="mt-6 inline-flex items-center gap-2 font-semibold text-primary">Learn more <ArrowRight size={17}/></Link></article>}
export function EventCard({item}:{item:EventItem}){return <article className="card-lift rounded-2xl border bg-card p-6"><time className="text-sm font-semibold text-accent">{item.displayDate}</time><h3 className="mt-2 text-2xl text-primary">{item.title}</h3><p className="mt-3 flex items-center gap-2 text-sm text-muted-foreground"><MapPin size={16}/>{item.venue}</p><p className="mt-4 text-muted-foreground">{item.description}</p><Link to="/events/$slug" params={{slug:item.slug}} className="mt-5 inline-flex items-center gap-2 font-semibold text-primary">Event details <ArrowRight size={17}/></Link></article>}
export function PostCard({item}:{item:Post}){return <article className="card-lift rounded-2xl border bg-card p-7"><p className="text-xs font-semibold uppercase tracking-[.16em] text-accent">{item.category} · {item.date}</p><h3 className="mt-3 text-2xl text-primary">{item.title}</h3><p className="mt-3 text-muted-foreground">{item.excerpt}</p><Link to="/blog/$slug" params={{slug:item.slug}} className="mt-5 inline-flex items-center gap-2 font-semibold text-primary">Read story <ArrowRight size={17}/></Link></article>}
export function PersonCard({item}:{item:Person}){return <article className="rounded-2xl border bg-card p-6"><div className="mb-5 flex h-16 w-16 items-center justify-center rounded-full bg-secondary font-display text-2xl text-primary">{item.name.split(' ').map(x=>x[0]).join('')}</div><h3 className="text-xl text-primary">{item.name}</h3><p className="text-sm font-semibold text-accent">{item.role}</p><p className="mt-2 text-sm text-muted-foreground">{item.bio}</p></article>}
export function PageHero({title,crumb,copy}:{title:string;crumb?:string;copy?:string}){return <section className="relative flex min-h-80 items-end overflow-hidden bg-primary pt-28 text-primary-foreground"><img src={mountain} alt="Himalayan ridges and a village in Uttarakhand" className="absolute inset-0 h-full w-full object-cover opacity-35"/><div className="absolute inset-0 bg-primary/70"/><div className="container-site relative z-10 pb-14"><p className="mb-3 text-sm font-semibold uppercase tracking-[.16em] text-brass">Home / {crumb||title}</p><h1>{title}</h1>{copy&&<p className="mt-4 max-w-2xl text-primary-foreground/80">{copy}</p>}</div></section>}
export const meta=(title:string,description:string)=>({meta:[{title:`${title} — UKDB UK`},{name:'description',content:description},{property:'og:title',content:`${title} — UKDB UK`},{property:'og:description',content:description},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]});
